# Dominio / FQDN donde servirá iTop
itop_server_name: itop.ejemplo.local

# Ruta de instalación
itop_web_root: /var/www/itop

# Versión/descarga de iTop
# Recomendado: fijar versión estable publicada por Combodo.
# Puedes mirar versiones aquí: https://github.com/Combodo/iTop/releases
itop_version: "3.1.1-1"
itop_download_url: "https://sourceforge.net/projects/itop/files/itop/3.1.1-1/iTop-3.1.1-1-12561.zip"

# DB (MariaDB)
# itop_db_name: itop
# itop_db_user: itop
# itop_db_password: "CambiaEstaPasswordSegura"
# itop_db_host: "localhost"

# PHP / Apache (PHP-FPM 8.1 en Ubuntu 22.04)
php_version: "8.1"
php_fpm_pool: "www"
php_memory_limit: "1024"
php_upload_max_filesize: "32M"
php_post_max_size: "64M"
php_max_execution_time: "300"

# HTTPS (opcional). Si usas SSL termina el vhost a tu gusto.
enable_https: false
