---
# ============================================
# ACTUALIZACION DEL SISTEMA
# ============================================

- name: Actualizar cache APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  retries: 5
  delay: 15
  register: apt_update
  until: apt_update is succeeded
  tags: ['install', 'update']

# ============================================
# INSTALACION DE APACHE Y PHP
# ============================================

- name: Paquetes base para manejar PPAs
  apt:
    name:
      - software-properties-common
      - ca-certificates
    state: present
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: add PPA de Ondrej para PHP
  command: add-apt-repository -y ppa:ondrej/php
  args:
    creates: /etc/apt/sources.list.d/ondrej-ubuntu-php*
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: apt update
  apt:
    update_cache: yes
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: Instalar Apache, PHP-FPM {{ php_version }}, y utilidades
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid
      - unzip
      - curl
      - graphviz
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-cli
      - php{{ php_version }}-xml
      - php{{ php_version }}-gd
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
      - php{{ php_version }}-soap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-apcu
      - php{{ php_version }}-ldap
      - php{{ php_version }}-imap
      - php{{ php_version }}-intl
    state: present
  tags: ['install']

- name: Habilitar módulos de Apache necesarios
  command: a2enmod "{{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  loop:
    - proxy
    - proxy_fcgi
    - setenvif
    - headers
    - expires
    - rewrite
  notify: Restart Apache
  tags: ['config']

# ============================================
# CONFIGURACION DE PHP
# ============================================

- name: Ajustes PHP específicos para iTop
  template:
    src: php.ini.d-itop.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/conf.d/99-itop.ini
    mode: "0644"
  notify: Restart PHP-FPM
  tags: ['config']

# ============================================
# VERIFICACION Y PREPARACION DE DIRECTORIOS
# ============================================

- name: Verificar directorio base de iTop (itop_web_root)
  stat:
    path: "{{ itop_web_root }}"
  register: install_dir
  tags: ['install']

- name: Asegurar directorio base de iTop
  file:
    path: "{{ itop_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  tags: ['install']

# Señal de "código presente": índice público de iTop
- name: Verificar si ya existe el árbol web de iTop
  stat:
    path: "{{ itop_web_root }}/web/index.php"
  register: itop_web_present
  tags: ['install']

# Señal de "setup completado": existe config-itop.php
- name: Verificar si iTop ya está configurado (config-itop.php)
  stat:
    path: "{{ itop_web_root }}/web/conf/production/config-itop.php"
  register: itop_configured
  tags: ['install']

# Crear estructura para que el wizard pueda escribir config-itop.php
- name: Crear estructura de conf/production con permisos para www-data
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
  loop:
    - "{{ itop_web_root }}/web/conf"
    - "{{ itop_web_root }}/web/conf/production"
  tags: ['config', 'permissions']

# ============================================
# DESCARGA E INSTALACION DE ITOP
# ============================================

- name: Descargar iTop {{ itop_version }}
  get_url:
    url: "{{ itop_download_url }}"
    dest: /tmp/itop.zip
    mode: "0644"
    timeout: 120
    headers:
      User-Agent: ansible-itop-installer
  when: not itop_web_present.stat.exists
  tags: ['install']

- name: Descomprimir iTop en webroot
  unarchive:
    src: /tmp/itop.zip
    dest: "{{ itop_web_root }}"
    remote_src: yes
    extra_opts: ["-q"]
    owner: www-data
    group: www-data
  when: not itop_web_present.stat.exists
  notify: Fix permissions
  tags: ['install']

- name: Limpiar archivo zip temporal
  file:
    path: /tmp/itop.zip
    state: absent
  when: not itop_web_present.stat.exists
  tags: ['install']

# ============================================
# CONFIGURACION DE APACHE
# ============================================

- name: VirtualHost para iTop (DocumentRoot -> {{ itop_web_root }}/web)
  template:
    src: itop-apache-vhost.conf.j2
    dest: /etc/apache2/sites-available/itop.conf
  notify: Restart Apache
  tags: ['config']

- name: Deshabilitar sitio por defecto
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: Restart Apache
  tags: ['config']

- name: Habilitar sitio iTop
  file:
    src: /etc/apache2/sites-available/itop.conf
    dest: /etc/apache2/sites-enabled/itop.conf
    state: link
  notify: Restart Apache
  tags: ['config']

- name: Eliminar index.html que pueden tapar iTop
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /var/www/html/index.html
    - "{{ itop_web_root }}/index.html"
    - "{{ itop_web_root }}/web/index.html"
  notify: Restart Apache
  tags: ['config']

# ============================================
# PERMISOS Y PROPIEDAD
# ============================================

- name: Asegurar propiedad recursiva para www-data
  file:
    path: "{{ itop_web_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: "0755"
  notify: Fix permissions
  tags: ['config', 'permissions']

- name: Asegurar permisos recursivos (dirs 755, files 644)
  shell: |
    find {{ itop_web_root }} -type d -exec chmod 755 {} +;
    find {{ itop_web_root }} -type f -exec chmod 644 {} +;
  args:
    warn: false
  tags: ['permissions']

- name: Crear directorios de datos con permisos especiales
  file:
    path: "{{ itop_web_root }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0770"
  loop:
    - data
    - log
    - env-production
    - conf
  ignore_errors: yes
  tags: ['config', 'permissions']

# Marker para señales externas (initialize-itop.sh / monitoreo)
- name: Crear marker de provisión en EFS
  copy:
    dest: "{{ itop_web_root }}/.itop_provisioned"
    content: "provisioned at {{ ansible_date_time.iso8601 }}"
    owner: www-data
    group: www-data
    mode: "0644"
  when: itop_web_present.stat.exists
  tags: ['info']

# ============================================
# INICIAR SERVICIOS
# ============================================

- name: Iniciar y habilitar servicios
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - php{{ php_version }}-fpm
    - apache2
  tags: ['service']

# ============================================
# INFORMACION FINAL
# ============================================

- name: Mostrar información de acceso
  debug:
    msg: >-
      {{
        [
          "================================================",
          "iTop desplegado correctamente",
          "================================================",
          itop_configured.stat.exists
            | ternary(
                "URL: http://" ~ ansible_default_ipv4.address ~ "/",
                "URL de setup: http://" ~ ansible_default_ipv4.address ~ "/setup/"
              ),
          "Directorio: " ~ itop_web_root,
          "",
          (itop_configured.stat.exists
            | ternary(
                "CONFIGURACION: detectada (config-itop.php presente en web/conf/production)",
                "CONFIGURACION MANUAL REQUERIDA: 1) Accede al setup web 2) Ingresa credenciales RDS 3) Completa el wizard"
              )
          ),
          "================================================"
        ]
      }}
  tags: ['info']
