---
# ============================================
# ESPERAR QUE EL SISTEMA ESTE LISTO
# ============================================

- name: Esperar que dpkg/apt estén disponibles
  shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 ; do
      echo "Esperando que dpkg esté disponible..."
      sleep 2
    done
  changed_when: false
  tags: ['install']

# ============================================
# ACTUALIZACION DEL SISTEMA
# ============================================

- name: Actualizar cache APT
  apt:
    update_cache: yes
    cache_valid_time: 3600
  retries: 3
  delay: 10
  register: apt_update
  until: apt_update is succeeded
  tags: ['install', 'update']

# ============================================
# INSTALACION DE APACHE Y PHP
# ============================================

- name: Paquetes base para manejar PPAs
  apt:
    name: 
      - software-properties-common
      - ca-certificates
    state: present
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: add PPA de Ondrej para PHP
  command: add-apt-repository -y ppa:ondrej/php
  args:
    creates: /etc/apt/sources.list.d/ondrej-ubuntu-php*
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: apt update
  apt:
    update_cache: yes
  when: ansible_distribution_release in ['noble','mantic']
  tags: ['install']

- name: Instalar Apache, PHP-FPM {{ php_version }}, y utilidades
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid
      - unzip
      - curl
      - graphviz
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-cli
      - php{{ php_version }}-xml
      - php{{ php_version }}-gd
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
      - php{{ php_version }}-soap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-apcu
      - php{{ php_version }}-ldap
      - php{{ php_version }}-imap
      - php{{ php_version }}-intl
    state: present
  tags: ['install']

- name: Habilitar módulos de Apache necesarios
  command: a2enmod "{{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  loop:
    - proxy
    - proxy_fcgi
    - setenvif
    - headers
    - expires
    - rewrite
  notify: Restart Apache
  tags: ['config']

# ============================================
# CONFIGURACION DE PHP
# ============================================

- name: Ajustes PHP específicos para iTop
  template:
    src: php.ini.d-itop.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/conf.d/99-itop.ini
    mode: "0644"
  notify: Restart PHP-FPM
  tags: ['config']

# ============================================
# VERIFICACION Y PREPARACION DE DIRECTORIOS
# ============================================

- name: Verificar que el directorio de instalación existe (EFS debe estar montado)
  stat:
    path: "{{ itop_web_root }}"
  register: install_dir
  tags: ['install']

- name: Asegurar directorio base de iTop
  file:
    path: "{{ itop_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  when: install_dir.stat.exists
  tags: ['install']

- name: Verificar si iTop ya está instalado
  stat:
    path: "{{ itop_web_root }}/web/index.php"
  register: itop_installed
  tags: ['install']

# ============================================
# DESCARGA E INSTALACION DE ITOP
# ============================================

- name: Descargar iTop {{ itop_version }}
  get_url:
    url: "{{ itop_download_url }}"
    dest: /tmp/itop.zip
    mode: "0644"
    timeout: 120
    headers:
      User-Agent: ansible-itop-installer
  when: not itop_installed.stat.exists
  tags: ['install']

- name: Descomprimir iTop en webroot
  unarchive:
    src: /tmp/itop.zip
    dest: "{{ itop_web_root }}"
    remote_src: yes
    extra_opts: [ "-q" ]
    owner: www-data
    group: www-data
  when: not itop_installed.stat.exists
  notify: Fix permissions
  tags: ['install']

- name: Limpiar archivo zip temporal
  file:
    path: /tmp/itop.zip
    state: absent
  when: not itop_installed.stat.exists
  tags: ['install']

# ============================================
# CONFIGURACION DE APACHE
# ============================================

- name: VirtualHost para iTop
  template:
    src: itop-apache-vhost.conf.j2
    dest: /etc/apache2/sites-available/itop.conf
  notify: Restart Apache
  tags: ['config']

- name: Deshabilitar sitio por defecto
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: Restart Apache
  tags: ['config']

- name: Habilitar sitio iTop
  file:
    src: /etc/apache2/sites-available/itop.conf
    dest: /etc/apache2/sites-enabled/itop.conf
    state: link
  notify: Restart Apache
  tags: ['config']

# ============================================
# PERMISOS Y PROPIEDAD
# ============================================

- name: Asegurar permisos y propiedad del árbol de iTop
  file:
    path: "{{ itop_web_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: "0755"
  notify: Fix permissions
  tags: ['config', 'permissions']

- name: Crear directorios de datos con permisos especiales
  file:
    path: "{{ itop_web_root }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0770'
  loop:
    - data
    - log
    - env-production
    - conf
  ignore_errors: yes
  tags: ['config', 'permissions']

# ============================================
# INICIAR SERVICIOS
# ============================================

- name: Iniciar y habilitar servicios
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - php{{ php_version }}-fpm
    - apache2
  tags: ['service']

# ============================================
# INFORMACION FINAL
# ============================================

- name: Mostrar información de acceso
  debug:
    msg:
      - "================================================"
      - "iTop desplegado correctamente"
      - "================================================"
      - "URL de setup: http://{{ ansible_default_ipv4.address }}/setup/"
      - "Directorio: {{ itop_web_root }}"
      - ""
      - "CONFIGURACIÓN MANUAL REQUERIDA:"
      - "1. Accede al setup web"
      - "2. Ingresa los