- name: Actualizar cache APT
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Paquetes base para manejar PPAs
  apt:
    name: [software-properties-common, ca-certificates]
    state: present
  when: ansible_distribution_release in ['noble','mantic'] # Ubuntu 24.04+

- name: add PPA de Ondrej para PHP
  command: add-apt-repository -y ppa:ondrej/php
  args:
    creates: /etc/apt/sources.list.d/ondrej-ubuntu-php*
  when: ansible_distribution_release in ['noble','mantic']

- name: apt update
  apt:
    update_cache: yes
  when: ansible_distribution_release in ['noble','mantic']

- name: Instalar Apache, PHP-FPM {{ php_version }}, MariaDB y utilidades
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid
      - mariadb-server
      - unzip
      - curl
      - graphviz
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-cli
      - php{{ php_version }}-xml
      - php{{ php_version }}-gd
      - php{{ php_version }}-zip
      - php{{ php_version }}-curl
      - php{{ php_version }}-soap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-apcu
      - php{{ php_version }}-ldap
      - php{{ php_version }}-imap
      - php{{ php_version }}-intl
    state: present

- name: Habilitar módulos de Apache necesarios
  command: a2enmod "{{ item }}"
  args:
    creates: "/etc/apache2/mods-enabled/{{ item }}.load"
  loop:
    - proxy
    - proxy_fcgi
    - setenvif
    - headers
    - expires
    - rewrite
  notify: Restart Apache

- name: Ajustes PHP específicos para iTop
  template:
    src: php.ini.d-itop.ini.j2
    dest: /etc/php/{{ php_version }}/fpm/conf.d/99-itop.ini
    mode: "0644"
  notify: Restart PHP-FPM

- name: Asegurar directorio base de iTop
  file:
    path: "{{ itop_web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Descargar iTop {{ itop_version }}
  get_url:
    url: "{{ itop_download_url }}"
    dest: /tmp/itop.zip
    mode: "0644"
    timeout: 120
    headers:
      User-Agent: ansible-itop-installer

- name: Descomprimir iTop en webroot
  unarchive:
    src: /tmp/itop.zip
    dest: "{{ itop_web_root }}"
    remote_src: yes
    extra_opts: [ "-q" ]
  notify: Fix permissions

- name: Instalar dependencias de Python para MySQL (Debian/Ubuntu)
  become: true
  apt:
    name: python3-pymysql
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Instalar dependencias de Python para MySQL (RedHat/Fedora)
  become: true
  dnf:
    name: python3-PyMySQL
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

# - name: Crear base de datos (MariaDB)
#   become: true
#   community.mysql.mysql_db:
#     name: "{{ itop_db_name }}"
#     state: present
#     encoding: utf8mb4
#     collation: utf8mb4_unicode_ci
#     login_unix_socket: /var/run/mysqld/mysqld.sock

# - name: Crear usuario de BD y permisos (MariaDB)
#   become: true
#   community.mysql.mysql_user:
#     name: "{{ itop_db_user }}"
#     password: "{{ itop_db_password }}"
#     host: "localhost"
#     priv: "{{ itop_db_name }}.*:ALL"
#     state: present
#     login_unix_socket: /var/run/mysqld/mysqld.sock

# VirtualHost Apache que pasa PHP a PHP-FPM
- name: VirtualHost para iTop
  template:
    src: itop-apache-vhost.conf.j2
    dest: /etc/apache2/sites-available/itop.conf
  notify: Restart Apache

- name: Deshabilitar sitio por defecto
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: Restart Apache

- name: Habilitar sitio iTop
  file:
    src: /etc/apache2/sites-available/itop.conf
    dest: /etc/apache2/sites-enabled/itop.conf
    state: link
  notify: Restart Apache

- name: Asegurar permisos y propiedad del árbol de iTop
  become: true
  file:
    path: "{{ itop_web_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: "0755"

- name: Iniciar y habilitar servicios
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - php{{ php_version }}-fpm
    - apache2
    - mariadb

